config/routes.rb
Rails.application.routes.draw do
  get "signup", to: "users#new"
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy", as: "logout"
  resources :users  #, except: [:new, :show]
  resources :students
  root "users#principal" 
  get "about", to: "users#about"
  get "contact", to: "users#contact"
  get "dashboard", to: "users#dashboard"
  get "index", to: "users#index"
  match ':controller(/:action(/:id))',:via=> :get
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

#class Ability
#  include CanCan::Ability

 # def initialize(user)
  #  user ||= User.new  # guest user (not logged in)
   # can :manage , :all
   # if user.admin?
     # can :manage, :all
   #else
    #  can :read, :all
   #end
    # Define abilities for the passed in user here. For example:
    #
   
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  
end

app/models/student.rb
class Student < ApplicationRecord
    has_secure_password
    has_many_attached :files

end

app/models/user.rb
class User < ApplicationRecord
   has_secure_password
    has_many_attached :files
 validates :Nom,  
      presence: true  
validates :Prénom,  
    presence: true  
validates :Date_de_naissance,  
    presence: true  
validates :sexe,  
    presence: true  
validates :Adresse,  
    presence: true  
validates :Ville,  
    presence: true  
validates :Téléphone,  
    presence: true  
validates :spécialité,  
    presence: true  
validates :password_digest,  
    presence: true  
validates :code_postal,  
    presence: true  
validates :Nationalité,  
    presence: true  
validates :commune,  
    presence: true  
validates :files,  
    presence: true  
validates :Email,  
    presence: true,  
    uniqueness: true,  
    format: {  
      with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i  
    }  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authorized
    helper_method :current_user, :logged_in?
def current_user
  @current_user ||= User.find(session[:user_id]) if session[:user_id]
end
 
def logged_in?
  !!current_user
end
def require_user
  if !logged_in?
    flash[:alert] = "You must be logged in to perform that action."
    redirect_to login_path
  end
end
def authorized
  redirect_to root_path unless logged_in?
end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authorized, only: [:new, :create]
    def create
        user = User.find_by(Email: params[:session][:Email].downcase)
        if user && user.authenticate(params[:session][:password])
          session[:user_id] = user.id
          flash[:notice] = "Logged in successfully."
          redirect_to user
   
        else
          flash.now[:alert] = "There was something wrong with your login details."
         
          render 'new'
        end
      end
       
      def destroy
        session[:user_id] = nil
        flash[:notice] = "You have been logged out."
        redirect_to root_path
      end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student , only: [:show, :edit, :update, :destroy ]

  # GET /students or /students.json
  def principal
    
  end
  
  def index
    @students = Student.all
  end

    # GET /students/1 or /students/1.json
  def show
  #  @student = Student.find(params[:id])
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  # @student = Student.find(params[:id])
  end

  # POST /students or /students.json
  def create
    @student = Student.new(student_params)
    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: "Student was successfully created." }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1 or /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: "Student was successfully updated." }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1 or /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: "Student was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def student_params
      params.require(:student).permit(:Nom, :Prénom, :Date_de_naissance, :sexe, :Adresse, :Ville, :Téléphone, :spécialité, :password_digest, :code_postal, :Email, :Nationalité, :commune, files: [])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authorized, only: [:new, :create, :index , :about , :principal, :contact]
    
 def new
     @user = User.new
 end

 def create
    @user = User.new(user_params)
    if @user.save
    # UserMailer.registration_confirmation(@user).deliver
      flash[:notice] = "Successfully User created."
      render 'show' 
     
    else
      render 'new'
    end
  end
  def show
    @user = User.find(params[:id])
  end
  def index
    @users = User.all
  end
  def edit
    @user = User.find(params[:id])
  end
  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to @user
    else
      render :edit
    end
  end
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    redirect_to root_path
  end
  def about
    
  end
  def principal
    
  end
  def contact
    
  end
  def dashboard
    @users = User.all
  end
    
  
  
  
  
  
 private
  
 def user_params
  params.require(:user).permit(:Nom, :Prénom, :Date_de_naissance, :sexe, :Adresse, :Ville, :Téléphone, :spécialité, :password, :code_postal, :Email, :Nationalité, :commune, files: [])
end
 


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>University</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  
  <div class="container-">
    <%= yield %>
    </div>
  </body>
</html>

app/views/students/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
   <div class="container">
  <a class="navbar-brand" href="#">AbbesLaghrour</a>
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to 'Home', root_path, class:"nav-link" %>
      </li> <li class="nav-item active">
           <%= link_to 'About', about_path, class:"nav-link" %>
      </li>
      <li class="nav-item active">
          <%= link_to 'Contact', contact_path, class:"nav-link nvlk" %>
      </li>
      <li class="nav-item active">
          <%= link_to 'Dashboard', dashboard_path, class:"nav-link nvlk" %>
      </li>
    </ul>
  </div>
  <% if current_user %>
  Logged in as <%= current_user.Email %>
 <%= button_to "Logout" ,logout_path, class:"btn btn-danger", method: :delete %>
     <% else %>
     <%= button_to "Sign-Up" ,signup_path, class:"btn btn-primary mr-sm-4", method: :get %>
     <%= button_to "Login" ,login_path, class:"btn btn-info  my-2 my-sm-1", method: :get %>
     
     <% end %>
     </div>
</nav>

app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Students</h1>
<table class=" table table-bordered table-hover">
  <thead class="thead-dark">
    <tr>
      <th>Nom</th>
      <th>Prénom</th>
      <th>Date de naissance</th>
      <th>Sexe</th>
      <th>Adresse</th>
      <th>Ville</th>
      <th>Téléphone</th>
      <th>Spécialité</th>
      <th>Code postal</th>
      <th>Email</th>
      <th>Nationalité</th>
      <th>Commune</th>
      <th>Files</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.Nom %></td>
        <td><%= student.Prénom %></td>
        <td><%= student.Date_de_naissance %></td>
        <td><%= student.sexe %></td>
        <td><%= student.Adresse %></td>
        <td><%= student.Ville %></td>
        <td><%= student.Téléphone %></td>
        <td><%= student.spécialité %></td>
        <td><%= student.code_postal %></td>
        <td><%= student.Email %></td>
        <td><%= student.Nationalité %></td>
        <td><%= student.commune %></td>
        <td ><% student.files.each do |file| %>
   <%= link_to file.filename, rails_blob_path(file, disposition: :attachment) %>
 <% end %>
       </td>

         
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<%= link_to 'New Student', new_student_path %>

app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nom:</strong>
  <%= @student.Nom %>
</p>

<p>
  <strong>Prénom:</strong>
  <%= @student.Prénom %>
</p>

<p>
  <strong>Date de naissance:</strong>
  <%= @student.Date_de_naissance %>
</p>

<p>
  <strong>Sexe:</strong>
  <%= @student.sexe %>
</p>

<p>
  <strong>Adresse:</strong>
  <%= @student.Adresse %>
</p>

<p>
  <strong>Ville:</strong>
  <%= @student.Ville %>
</p>

<p>
  <strong>Téléphone:</strong>
  <%= @student.Téléphone %>
</p>

<p>
  <strong>Spécialité:</strong>
  <%= @student.spécialité %>
</p>

<p>
  <strong>Password:</strong>
  <%= @student.password_digest %>
</p>

<p>
  <strong>Code postal:</strong>
  <%= @student.code_postal %>
</p>

<p>
  <strong>Email:</strong>
  <%= @student.Email %>
</p>

<p>
  <strong>Nationalité:</strong>
  <%= @student.Nationalité %>
</p>

<p>
  <strong>Commune:</strong>
  <%= @student.commune %>
</p>
 
 <% @student.files.each do |file| %>
   <%= link_to file.filename, rails_blob_path(file, disposition: :attachment) %>
 <% end %>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>

app/views/users/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">
    <img src="/docs/4.3/assets/brand/bootstrap-solid.svg" width="30" height="30" class="d-inline-block align-top" alt="">
    Bootstrap</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/users/contact.html.erb
  <%= render "students/navbar" %>
<div class="container">
<div class="jumbotron jpm">
  <h1 class="display-4">Hello, Student!</h1>
  <p class="lead">This is a simple contact service, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
  <hr class="my-4">
  <p>Call this number if there is a problem: +213 00 00 00 00 00 .</p>
  <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
</div>
</div>

app/views/users/dashboard.html.erb
   <%= render "students/navbar" %>
 <% if notice %><p id="notice" class="alert alert-info"><%= notice %></p> <% end %>
 <% if current_user && current_user.admin%>
<h1 class="ten">Students:</h1>
<div class ="table-responsive-sm">
<table class=" table table-bordered table-hover">
  <thead class="six">
    <tr>
      <th>Last Name</th>
      <th>First Name</th>
      <th>Date of birth</th>
      <th>Sex</th>
      <th>Adress</th>
      <th>City</th>
      <th>Phone</th>
      <th>Specialty</th>
      <th>Postal code</th>
      <th>E-mail</th>
      <th>Nationality</th>
      <th>Common</th>
      <th>Files</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.Nom %></td>
        <td><%= user.Prénom %></td>
        <td><%= user.Date_de_naissance %></td>
        <td><%= user.sexe %></td>
        <td><%= user.Adresse %></td>
        <td><%= user.Ville %></td>
        <td><%= user.Téléphone %></td>
        <td><%= user.spécialité %></td>
        <td><%= user.code_postal %></td>
        <td><%= user.Email %></td>
        <td><%= user.Nationalité %></td>
        <td><%= user.commune %></td>
        <td ><% user.files.each do |file| %>
   <%= link_to file.filename, rails_blob_path(file, disposition: :inline) %>
 <% end %>
       </td>
        
        <td>
           <%= link_to 'Show', user, class:"btn btn-info qq" %></td>
     
        <td><%= link_to 'Edit', edit_user_path(user), class:"btn btn-info qq" %></td>
        <td><%= link_to 'Destroy', user, class:"btn btn-info qq" ,method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    
    <% end %>
  </tbody>
</table>
</div>
<br>
    
      <% end %>
    
  

app/views/users/edit.html.erb
  <%= render "students/navbar" %>
  <%= render 'ddr', user: @user%>
<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
   <%= render "students/navbar" %>
 <% if notice %><p id="notice" class="alert alert-info"><%= notice %></p> <% end %>
 <% if current_user && current_user.admin%>
<h1 class="ten">Students:</h1>
<div class ="table-responsive-sm">
<table class=" table table-bordered table-hover">
  <thead class="six">
    <tr>
      <th>Nom</th>
      <th>Prénom</th>
      <th>Date de naissance</th>
      <th>Sexe</th>
      <th>Adresse</th>
      <th>Ville</th>
      <th>Téléphone</th>
      <th>Spécialité</th>
      <th>Code postal</th>
      <th>Email</th>
      <th>Nationalité</th>
      <th>Commune</th>
      <th>Files</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.Nom %></td>
        <td><%= user.Prénom %></td>
        <td><%= user.Date_de_naissance %></td>
        <td><%= user.sexe %></td>
        <td><%= user.Adresse %></td>
        <td><%= user.Ville %></td>
        <td><%= user.Téléphone %></td>
        <td><%= user.spécialité %></td>
        <td><%= user.code_postal %></td>
        <td><%= user.Email %></td>
        <td><%= user.Nationalité %></td>
        <td><%= user.commune %></td>
        <td ><% user.files.each do |file| %>
   <%= link_to file.filename, rails_blob_path(file, disposition: :inline) %>
 <% end %>
       </td>
        
        <td>
           <%= link_to 'Show', user, class:"btn btn-info qq" %></td>
     
        <td><%= link_to 'Edit', edit_user_path(user), class:"btn btn-info qq" %></td>
        <td><%= link_to 'Destroy', user, class:"btn btn-info qq" ,method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
 
      
    <% end %>
  </tbody>
</table>
</div>
<br>
     
      <% end %>

app/views/users/principal.html.erb
  <!DOCTYPE html>
  <html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Homepage</title>
  </head>
  <body>
    <div class="header">
     <div class="overlay">
      <div class="container">
       <div class="navbar">
       <div class="container">
       <nav class="navbar navbar-expand-lg navbar-dark bg-transparent">
  <a class="navbar-brand nv" href="#">  <span class="aa">Abbes<span class="main-color">Laghrour</span></span></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

        <div class="container">
          <div class="container">
          <div class="container">
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active nvitem">
        <%= link_to 'Home', root_path, class:"nav-link nvlk" %>
      </li>
      <li class="nav-item active nvitem">
          <%= link_to 'About', about_path, class:"nav-link nvlk" %>
      </li>
      <li class="nav-item active nvitem">
         <%= link_to 'Contact', contact_path, class:"nav-link nvlk" %>
      </li>
      <li class="nav-item active nvitem">
        <%= link_to 'Dashboard', dashboard_path, class:"nav-link nvlk" %>
      </li>

    </ul>
    </div>
    </div>
  </div>
</nav>
</div>
       </div>
         <div class="intro text-center">
            <h1 class="upper">We Signup <span class="main-color">In University</span></h1>
            <p class="ss"> Lorem ipsum dolor sit amet consectetur adipisicing elit.
            <br> Assumenda inventore saepe debitis, autem mollitia ratione.<br>
              adipisci 
            repudiandae eveniet error labore tempora modi neque est delectus libero!</p>
             <div class="buttons">
            <button class="qq"> <%= button_to'Signup', signup_path, class:"btn qq", method: :get %></button>
            <button class="qq"> <%= button_to'Login',  login_path, class:"btn qq", method: :get %></button>
             </div>
         </div>
         
      </div>
     </div>
    </div>
        <div class="aboutus">
          <div class="container">
            <h1>About Us</h1>
            <div class="row">
              <div class="col">
                <p>
                There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form,
                 by injected humour,
                 or randomised words which don't look even slightly believable.
                 If you are going to use a passage of Lorem Ipsum,
                  you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as ne
                   making this the first true generator on the Internet. 
                   <p>
                  It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures,
                   to generate Lorem Ipsum which looks reasonable.
                   The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.
                   </p>
                </p>
               
                  </div>
                 </div>
                </div>
              </div>
          <div class="services">
          <div class="container">
            <h1>Services</h1>
            <div class="row">

              <div class="col">
                <div class="card" >
                 <%= image_tag("image12.jpg", :height=>"200" ,:width=>"100", class:"card-img-top",:alt => "rss feed") %>
                    <div class="card-body">
                      <h5 class="card-title">Faculty</h5>
                      <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                      <a href="#" class="btn btn-primary">click to more</a>
                    </div>
                </div>
            </div>
           <div class="col">
                <div class="card" >
                     <%= image_tag("image13.jpg", :height=>"200" ,:width=>"100", class:"card-img-top",:alt => "rss feed") %>
                    <div class="card-body">
                      <h5 class="card-title">Department</h5>
                      <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                      <a href="#" class="btn btn-primary">click to more</a>
                    </div>
                </div>
            </div>

             <div class="col">
                <div class="card" >
                     <%= image_tag("zza.jpg", :height=>"200" ,:width=>"100", class:"card-img-top",:alt => "rss feed") %>
                    <div class="card-body">
                      <h5 class="card-title">Specialty</h5>
                      <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                      <a href="#" class="btn btn-primary">click to more</a>
                    </div>
                </div>
            </div>

             <div class="col">
                <div class="card">
                    <%= image_tag("images.jpg", :height=>"200" ,:width=>"100", class:"card-img-top",:alt => "rss feed") %>
                    <div class="card-body">
                      <h5 class="card-title">University</h5>
                      <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                      <a href="#" class="btn btn-primary">click to more</a>
                    </div>
                </div>
            </div>
         </div>
       </div>
    </div>
         
   
     

  </body>
  </html>

app/views/users/show.html.erb
  <%= render "students/navbar" %>
<% if notice %><p id="notice" class="alert alert-info"><%= notice %></p><% end %>
<div class="container">
<div class="card mb-3 elv" style="max-width: 540px;">
  <div class="row no-gutters">
    <div class="col-md-4">
      <%= image_tag("logo.jpeg", :height=>"35%" ,:width=>"100%" ,:alt => "rss feed") %>
    </div>
    <div class="col-md-8">
      <div class="card-body">
       <% if current_user && current_user.admin%>
        <h3 class="card-title">Manager</h3>
        <% else %>
         <h3 class="card-title">Student</h3>
         
         <% end %>
         
<p>
  <strong>Last Name:</strong>
  <%= @user.Nom %>
</p>

<p>
  <strong>First Name:</strong>
  <%=  @user.Prénom %>
</p>

<p>
  <strong>Date of birth:</strong>
  <%=  @user.Date_de_naissance %>
</p>

<p>
  <strong>Sex:</strong>
  <%=  @user.sexe %>
</p>

<p>
  <strong>Adress:</strong>
  <%=  @user.Adresse %>
</p>

<p>
  <strong>City:</strong>
  <%=  @user.Ville %>
</p>

<p>
  <strong>Phone:</strong>
  <%=  @user.Téléphone %>
</p>

<p>
  <strong>Specialty:</strong>
  <%=  @user.spécialité %>
</p>

<p>
  <strong>Password:</strong>
  <%=  @user.password_digest %>
</p>

<p>
  <strong>Postal Code:</strong>
  <%=  @user.code_postal %>
</p>

<p>
  <strong>E-mail:</strong>
  <%=  @user.Email %>
</p>

<p>
  <strong>Nationality:</strong>
  <%=  @user.Nationalité %>
</p>

<p>
  <strong>Common:</strong>
  <%=  @user.commune %>
</p>
 <p>
  <strong>Files:</strong>
 <%  @user.files.each do |file| %>
   <%= link_to file.filename, rails_blob_path(file, disposition: :inline) %>
 <% end %>
 </p>
  <%= link_to 'Edit', edit_user_path(@user),class:"btn btn-primary sh" %> 
<%= link_to 'Back', root_path, class:"btn btn-primary"%>
     </div>
    </div>
  </div>
</div>

</div>